const { execSync, spawn } = require('node:child_process');
const { generateKeyPairSync } = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');

console.log("═══════════════════════════════════════════════════════════════");
console.log("  🌍 Carbon DPI — 5-Minute Setup");
console.log("═══════════════════════════════════════════════════════════════\n");

// 1. Check prerequisites
try {
  execSync('node -v', { stdio: 'ignore' });
  execSync('npm -v', { stdio: 'ignore' });
  execSync('redis-cli ping', { stdio: 'ignore' });
} catch (e) {
  console.error("❌ Prerequisites missing. Please ensure Node.js, npm, and Redis are installed and running.");
  process.exit(1);
}
console.log("✅ Prerequisites satisfied (Node, npm, Redis).");

// 2. Generate keys
console.log("⏳ Generating Ed25519 identity keys...");
const { publicKey, privateKey } = generateKeyPairSync('ed25519');
const pubKeyBase64 = publicKey.export({ type: 'spki', format: 'der' }).toString('base64');
const privKeyBase64 = privateKey.export({ type: 'pkcs8', format: 'der' }).toString('base64');

// 3. Write .env
const envPath = path.join(__dirname, '..', '.env');
const envExamplePath = path.join(__dirname, '..', '.env.example');
let envContent = '';
if (fs.existsSync(envExamplePath)) {
  envContent = fs.readFileSync(envExamplePath, 'utf-8');
}
envContent += `\n# Generated by setup.js\nBECKN_ED25519_PUBLIC_KEY=${pubKeyBase64}\nBECKN_ED25519_PRIVATE_KEY=${privKeyBase64}\n`;
fs.writeFileSync(envPath, envContent);
console.log("✅ Keys generated and saved to .env");

// 4. Run DB migrations
console.log("⏳ Initializing local databases (SQLite)...");
try {
  execSync('npm run db:setup', { stdio: 'ignore', cwd: path.join(__dirname, '..') });
  console.log("✅ Databases migrated successfully.");
} catch (e) {
  console.error("❌ Database migration failed.");
  process.exit(1);
}

// 5. Build SDK
console.log("⏳ Building SDK...");
try {
  execSync('npm run build --filter=@carbon-dpi/sdk', { stdio: 'ignore', cwd: path.join(__dirname, '..') });
  console.log("✅ SDK built successfully.");
} catch (e) {
  console.error("❌ SDK build failed.");
  process.exit(1);
}

// 6. Start services
console.log("⏳ Starting core services (Registry, Gateway, Event Bus, Node)...");
const devProcess = spawn('npm', ['run', 'dev'], { cwd: path.join(__dirname, '..'), stdio: 'ignore', detached: true });
devProcess.unref();

// Give services a moment to start
console.log("⏳ Waiting for services to boot (10 seconds)...");
setTimeout(() => {
  console.log("✅ Services started in background.");
  console.log("\n🚀 Running solar simulator to issue first GIC...");
  
  try {
    const solarProcess = spawn('npm', ['run', 'dev'], { cwd: path.join(__dirname, '..', 'carbon-dpi-reference-solar'), stdio: 'inherit' });
    
    setTimeout(() => {
      solarProcess.kill();
      console.log("\n═══════════════════════════════════════════════════════════════");
      console.log("  🌍 Carbon DPI — Setup Complete");
      console.log("═══════════════════════════════════════════════════════════════\n");
      console.log("  ✅ Keys generated and saved to .env");
      console.log("  ✅ Databases migrated (SQLite)");
      console.log("  ✅ All 4 services running");
      console.log("  ✅ Telemetry ingested via Solar Simulator\n");
      console.log("  🏅 Your first GIC should be available soon!");
      console.log("  Check the event bus and reference node logs for details.");
      console.log("  (Run 'npm run dev' to see the logs)");
      console.log("\n═══════════════════════════════════════════════════════════════");
      process.exit(0);
    }, 15000); // Let solar run for 15s
  } catch (e) {
    console.error("❌ Solar simulation failed.");
    process.exit(1);
  }
}, 10000);
