import { randomUUID, generateKeyPairSync, sign } from 'node:crypto';

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * Carbon DPI — IoT Client SDK
 * ─────────────────────────────────────────────────────────────────────────────
 * 
 * This SDK provides the essential cryptographic functions for IoT hardware
 * to integrate securely with the Carbon DPI network.
 */

// ─────────────────────────────────────────────────────────────────────────────
// 1. Cryptography & Identity Management
// ─────────────────────────────────────────────────────────────────────────────

export interface KeyPair {
    publicKeyBase64: string;
    privateKeyPem: string;
}

/**
 * Generates an Ed25519 keypair for the hardware device.
 * In a real IoT environment, this would ideally be generated by a Secure Enclave / TPM.
 */
export function generateDeviceKeypair(): KeyPair {
    const { publicKey, privateKey } = generateKeyPairSync('ed25519');
    
    return {
        // Export public key as raw DER base64 so it can be verified easily by Ed25519 verifiers
        publicKeyBase64: publicKey.export({ type: 'spki', format: 'der' }).toString('base64'),
        // Export private key in PEM format for internal signing use
        privateKeyPem: privateKey.export({ type: 'pkcs8', format: 'pem' }).toString()
    };
}

/**
 * Input parameters for computing the Composite Identity Hash.
 * Must bind: identity, asset, device, GPS location, and timestamp.
 */
export interface CIHInput {
    identityHash: string;  // GSTIN / PAN / UDYAM / Aadhaar hash
    assetId: string;       // Physical asset registration ID
    deviceId: string;      // IoT device serial number / DID
    lat: number;           // GPS latitude
    lng: number;           // GPS longitude
    timestamp: string;     // ISO-8601 timestamp of binding
}

/**
 * Computes the Composite Identity Hash (CIH).
 * CIH = SHA-256(identityHash || assetId || deviceId || lat(6dp) || lng(6dp) || timestamp)
 * 
 * This MUST match the canonical definition in the reference node's sdk.ts.
 * The CIH cryptographically binds a verified identity to a physical asset,
 * IoT device, and GPS location — creating a tamper-evident identity anchor.
 */
export function computeCIH(params: CIHInput): string {
    const hash = require('node:crypto').createHash('sha256');
    const normalizedPayload = [
        params.identityHash.toLowerCase().trim(),
        params.assetId.trim(),
        params.deviceId.toLowerCase().trim(),
        params.lat.toFixed(6),
        params.lng.toFixed(6),
        params.timestamp.trim(),
    ].join("||");
    hash.update(normalizedPayload);
    return hash.digest('hex');
}


/**
 * Cryptographically signs a payload (usually CDIF telemetry) using the device's private Ed25519 key.
 */
export function signTelemetry(payload: object, privateKeyPem: string): string {
    // Standardize the payload to ensure deterministic signing
    const payloadStr = JSON.stringify(payload, Object.keys(payload).sort());
    return sign(null, Buffer.from(payloadStr), privateKeyPem).toString('base64');
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. Network Client
// ─────────────────────────────────────────────────────────────────────────────

export interface RawTelemetryData {
    sourceType: string;
    sourceId: string;
    timestamp: string;
    geolocation: { lat: number; lng: number };
    value: number;
    unit: string;
}

/**
 * A lightweight HTTP client to send signed telemetry to the Event Bus.
 */
export class EventBusClient {
    private eventBusUrl: string;
    private cihReference: string;
    private privateKeyPem: string;
    private apiKey: string;

    /**
     * @param eventBusUrl The ingestion URL (e.g., http://localhost:3004)
     * @param cihReference The device's Composite Identity Hash
     * @param privateKeyPem The device's private Ed25519 key for signing
     * @param apiKey The ingestion API key (optional, defaults to 'default-ingest-key')
     */
    constructor(eventBusUrl: string, cihReference: string, privateKeyPem: string, apiKey: string = "default-ingest-key") {
        this.eventBusUrl = eventBusUrl;
        this.cihReference = cihReference;
        this.privateKeyPem = privateKeyPem;
        this.apiKey = apiKey;
    }

    /**
     * Prepares, signs, and pushes a telemetry data point to the Event Bus.
     */
    async pushTelemetry(data: RawTelemetryData): Promise<boolean> {
        // Step 1: Create the base payload
        const basePayload = {
            id: `dp-${randomUUID()}`,
            cihReference: this.cihReference,
            sourceType: data.sourceType,
            sourceId: data.sourceId,
            timestamp: data.timestamp,
            geolocation: data.geolocation,
            value: data.value,
            unit: data.unit
        };

        // Step 2: Sign the payload
        const signature = signTelemetry(basePayload, this.privateKeyPem);

        // Step 3: Attach the signature
        const finalPayload = {
            ...basePayload,
            deviceSignature: signature
        };

        // Step 4: Dispatch to the Event Bus
        try {
            const res = await fetch(`${this.eventBusUrl}/v1/ingest`, {
                method: "POST",
                headers: { 
                    "Content-Type": "application/json",
                    "x-api-key": this.apiKey
                },
                body: JSON.stringify(finalPayload)
            });
            
            if (res.status === 202) {
                return true;
            } else {
                console.error(`[EventBusClient] Ingestion failed: ${res.status} ${res.statusText}`);
                const body = await res.text();
                console.error(body);
                return false;
            }
        } catch (error) {
            console.error(`[EventBusClient] Network error:`, error);
            return false;
        }
    }
}
