import { randomUUID, generateKeyPairSync, sign, createHash } from 'node:crypto';

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * Carbon DPI — IoT Client SDK v1.1.0
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * This SDK provides the essential cryptographic functions for IoT hardware
 * to integrate securely with the Carbon DPI network.
 *
 * CHANGELOG v1.1.0
 * - signTelemetry(): upgraded from shallow to recursive JCS sort (JSON
 *   Canonicalization Scheme). This matches the reference node's verification
 *   logic and the Python SDK's json.dumps(sort_keys=True) deep sort.
 * - EventBusClient: removed hardcoded default API key. Callers must supply
 *   their EVENT_BUS_API_KEY explicitly — prevents accidental production exposure.
 * - computeCIH(): unchanged — CIH inputs are the caller's responsibility.
 *   The commission timestamp MUST be fixed at device provisioning time, not
 *   at runtime. See the reference simulators for the correct pattern.
 */

// ─────────────────────────────────────────────────────────────────────────────
// 1. Cryptography & Identity Management
// ─────────────────────────────────────────────────────────────────────────────

export interface KeyPair {
    publicKeyBase64: string;
    privateKeyPem: string;
}

/**
 * Generates an Ed25519 keypair for the hardware device.
 * In a real IoT environment, this would ideally be generated by a Secure Enclave / TPM.
 *
 * IMPORTANT: Call this ONCE at device provisioning time and persist the result.
 * Do NOT regenerate on every boot — doing so will break the CIH chain.
 */
export function generateDeviceKeypair(): KeyPair {
    const { publicKey, privateKey } = generateKeyPairSync('ed25519');

    return {
        // Export public key as raw DER base64 for registry storage & Ed25519 verification
        publicKeyBase64: publicKey.export({ type: 'spki', format: 'der' }).toString('base64'),
        // Export private key in PEM format for internal signing use
        privateKeyPem: privateKey.export({ type: 'pkcs8', format: 'pem' }).toString()
    };
}

/**
 * Input parameters for computing the Composite Identity Hash.
 * Must bind: identity, asset, device, GPS location, and timestamp.
 *
 * CRITICAL: `timestamp` must be the device's COMMISSION DATE (a fixed ISO-8601
 * date like "2025-01-01T00:00:00.000Z"), NOT the current time. Using the current
 * time produces a different CIH on every boot, orphaning all past telemetry.
 */
export interface CIHInput {
    identityHash: string;  // GSTIN / PAN / UDYAM / Aadhaar hash
    assetId: string;       // Physical asset registration ID
    deviceId: string;      // IoT device serial number / DID
    lat: number;           // GPS latitude
    lng: number;           // GPS longitude
    timestamp: string;     // FIXED commission date — NOT new Date().toISOString()!
}

/**
 * Computes the Composite Identity Hash (CIH).
 * CIH = SHA-256(identityHash || assetId || deviceId || lat(6dp) || lng(6dp) || timestamp)
 *
 * This MUST match the canonical definition in the reference node's sdk.ts.
 * The CIH cryptographically binds a verified identity to a physical asset,
 * IoT device, and GPS location — creating a tamper-evident identity anchor.
 */
export function computeCIH(params: CIHInput): string {
    const hash = createHash('sha256');
    const normalizedPayload = [
        params.identityHash.toLowerCase().trim(),
        params.assetId.trim(),
        params.deviceId.toLowerCase().trim(),
        params.lat.toFixed(6),
        params.lng.toFixed(6),
        params.timestamp.trim(),
    ].join("||");
    hash.update(normalizedPayload);
    return hash.digest('hex');
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. JSON Canonicalization (JCS-compatible recursive sort)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Produces a deterministic JSON string with recursively sorted keys.
 *
 * This is the Carbon DPI canonical serialization format (JCS-compatible).
 * It matches:
 *   - The reference node's `JSON.stringify(recursiveSort(obj))`
 *   - The Python SDK's `json.dumps(sort_keys=True)`
 *   - The beckn-adapter's `toW3CVC` canonicalization
 *
 * IMPORTANT: Always use this (not plain JSON.stringify) when signing or
 * hashing payloads that must be verifiable across services or languages.
 */
export function jcsStringify(obj: unknown): string {
    const recursiveSort = (value: unknown): unknown => {
        if (Array.isArray(value)) return value.map(recursiveSort);
        if (value !== null && typeof value === 'object') {
            return Object.fromEntries(
                Object.keys(value as Record<string, unknown>)
                    .sort()
                    .map(k => [k, recursiveSort((value as Record<string, unknown>)[k])])
            );
        }
        return value;
    };
    return JSON.stringify(recursiveSort(obj));
}

/**
 * Cryptographically signs a payload (usually CDIF telemetry) using the device's
 * private Ed25519 key.
 *
 * Uses JCS recursive sort to ensure deterministic serialization across:
 *   - Different JS engines (Node.js, Deno, Bun)
 *   - Cross-language verification (Python SDK, Go verifiers)
 *   - Nested objects like `geolocation: {lat, lng}`
 */
export function signTelemetry(payload: object, privateKeyPem: string): string {
    // JCS-compatible recursive sort — cross-language compatible
    const payloadStr = jcsStringify(payload);
    return sign(null, Buffer.from(payloadStr), privateKeyPem).toString('base64');
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. Network Client
// ─────────────────────────────────────────────────────────────────────────────

export interface RawTelemetryData {
    sourceType: string;
    sourceId: string;
    timestamp: string;
    geolocation: { lat: number; lng: number };
    value: number;
    unit: string;
}

/**
 * A lightweight HTTP client to send signed telemetry to the Event Bus.
 *
 * @param eventBusUrl   The ingestion URL (e.g., http://localhost:3004)
 * @param cihReference  The device's Composite Identity Hash (computed ONCE at provisioning)
 * @param privateKeyPem The device's private Ed25519 key PEM for signing telemetry
 * @param apiKey        The Event Bus ingestion API key — REQUIRED, no default.
 *                      Set EVENT_BUS_API_KEY in your environment.
 */
export class EventBusClient {
    private eventBusUrl: string;
    private cihReference: string;
    private privateKeyPem: string;
    private apiKey: string;

    constructor(eventBusUrl: string, cihReference: string, privateKeyPem: string, apiKey: string) {
        if (!apiKey || apiKey.trim() === '') {
            throw new Error(
                '[EventBusClient] apiKey is required. ' +
                'Set EVENT_BUS_API_KEY in your environment and pass it explicitly. ' +
                'Do not use the default "default-ingest-key" in production.'
            );
        }
        this.eventBusUrl = eventBusUrl;
        this.cihReference = cihReference;
        this.privateKeyPem = privateKeyPem;
        this.apiKey = apiKey;
    }

    /**
     * Prepares, signs, and pushes a telemetry data point to the Event Bus.
     * Uses JCS recursive sort for the signature — verifiable by both the
     * Node.js reference node and the Python SDK.
     */
    async pushTelemetry(data: RawTelemetryData): Promise<boolean> {
        // Step 1: Build the canonical base payload (fields in alphabetical order
        // for clarity, but jcsStringify handles the actual sort at signing time)
        const basePayload = {
            id: `dp-${randomUUID()}`,
            cihReference: this.cihReference,
            sourceType: data.sourceType,
            sourceId: data.sourceId,
            timestamp: data.timestamp,
            geolocation: data.geolocation,
            value: data.value,
            unit: data.unit
        };

        // Step 2: Sign with JCS-compatible recursive sort
        const signature = signTelemetry(basePayload, this.privateKeyPem);

        // Step 3: Attach the signature
        const finalPayload = {
            ...basePayload,
            deviceSignature: signature
        };

        // Step 4: Dispatch to the Event Bus
        try {
            const res = await fetch(`${this.eventBusUrl}/v1/ingest`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "x-api-key": this.apiKey
                },
                body: JSON.stringify(finalPayload)
            });

            if (res.status === 202) {
                return true;
            } else {
                console.error(`[EventBusClient] Ingestion failed: ${res.status} ${res.statusText}`);
                const body = await res.text();
                console.error(body);
                return false;
            }
        } catch (error) {
            console.error(`[EventBusClient] Network error:`, error);
            return false;
        }
    }
}
